### ISSUE TITLE
Specify the return fields in get()

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#100]
I have a nested `coordinates` field that I want to search on, but I don't want it to get returned with the models. Is there a `hidden` array or something similar to make this happen ? The most obvious way would be for the `get()` or `paginate()`  methods to accept an array of fields to be returned (all by default if array is missing)

**Comment by sleimanx2** [comment]
At the moment it's not possible to do within the package, I use transformer (phephpleague/fractal). I hope I understood you well.

**Comment by Melcus** [comment]
I ended up doing the same thing. Thanks nonetheless.
