### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by sjakhetia** [sleimanx2/plastic#103]
Hi Team,

I want to apply filters on my search on the basis of user selection, User will select filter options from the screen and hit apply button that will show filtered results. Can you please provide, how I will implement this functionality?

Thank you in advance!

**Comment by Melcus** [comment]
Do you want the page to refresh?
> If not, are you using a JS framework ? Do you want the URL to change? 

In any case, take a look  here https://tirdeamihai.com/blog for some hints

If you still have any questions afterwards, let me know
