### ISSUE TITLE
[Proposal] Recreate and repopulate an index with no downtime

### ISSUE THREAD

**Issue by shaoshiva** [sleimanx2/plastic#115]
Hello,

I wrote a command for a project I worked on to recreate and repopulate an index with no downtime.

To understand how it works, here is an example of the output generated by the command on an existing aliased index :
```
$> php artisan index:recreate

Recreating default index « demo » ...
Index already exists and is an alias of « demo_2017-09-25_17-03-14 » (there will be no downtime).
New index name will be « demo_2017-09-25_17-03-19 ».
Creating index « demo_2017-09-25_17-03-19 » ...
Index successfully created !
Populating the index ...
Indexing documents of model « App\Models\Article » ...
Indexing chunk of 1000 documents ...
Indexing chunk of 79 documents ...
Documents of model successfully indexed !
Index successfully populated !
Moving alias from old indexes to new indexes ...
Removing alias « demo » from index « demo_2017-09-25_17-03-14 » ...
Alias successfully removed !
Adding alias « demo » to index « demo_2017-09-25_17-03-19 » ...
Alias successfully added !
Alias successfully moved from old indexes to new indexes !
Deleting index « demo_2017-09-25_17-03-14 »
Index successfully deleted !
Refreshing index « demo_2017-09-25_17-03-19 » ...
Index successfully refreshed !
Index successfully recreated !
```

Recreating the index with zero downtime is done using an alias [as recommended by the Elastic Search documentaiton](https://www.elastic.co/blog/changing-mapping-with-zero-downtime#_reindexing_your_data_with_zero_downtime). For what it's worth, I use this technique in production since 2 years and it work very well (the worst that can happen is that the index is not recreated).

For the moment, repopulation is done via a list of models defined in a configuration file, documents are saved by chunk.

@sleimanx2 Would you be interested by this feature ? If yes I can open a pull request.

**Comment by sleimanx2** [comment]
Nice ! , we could totally use this feature however since Elastic 5 I'm using the [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) api I find it more stable.

It might be a good idea to reimplement it using the new api.

One more think i think you're not copying the model mappings.

**Comment by shaoshiva** [comment]
Indeed the reindex API would be perfect in the case where an index already exists and would be far more efficient than reindexing from models.

However, I think we should keep the possibility of reindexing from the models to deal with the following cases:
- where no index already exists (first creation, rebuild after crash)
- where new fields are added to the mapping
- where the changes in the mappings are too complex

What would you think of an option on the command like `--reindex` that will force using the reindex API, or the opposite `--populate-from-models` to reindex from models ?

> One more think i think you're not copying the model mappings.

Yes it's possible, I have not worked so much on the mapping for now, I have to dig into this part.

**Comment by sleimanx2** [comment]
Lets start small , first lets create a command that populate the models data `plastic:populate` this command should accept an option `--mapping` that triggers the model mappings before populating the models.

What do you think ?

**Comment by shaoshiva** [comment]
Yes it would be a good start 👍

I will try to make a PR this week.

**Comment by jamesgraham** [comment]
Looking forward to this, let me know if help needed
