### ISSUE TITLE
Partial Matching?

### ISSUE THREAD

**Issue by marleybobby** [sleimanx2/plastic#119]
How can I achieve partial matching as described here? [https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-matching.html](url)

I would like to implement this functionality:
search-as-you-type—displaying the most likely results before the user has finished typing the search terms 

I tried to add * but without success
```php
Tag::search()
                ->multiMatch(['name'], '*'.$request->input('q').'*')->get();
```

**Comment by Melcus** [comment]
Try *querystring* . Check out this article for some guidance https://tirdeamihai.com/blog/google-like-search-with-vue-elasticsearch-laravel

**Comment by marleybobby** [comment]
Wow thanks for the fast response, really appreciate it. It was exactly what I was looking for 🥇  :)

**Comment by Melcus** [comment]
Glad I could help :)
