### ISSUE TITLE
Cannot install plastic

### ISSUE THREAD

**Issue by zakiaziz** [sleimanx2/plastic#14]
At first plastic could not install due to a dependency to laravel 5.2. After upgrading to 5.2 `composer require sleimanx2/plastic` downloaded the files into `vendor/sleimanx2`

Running `php artisan vendor:publish` did not publish any files into `config/` nor did it create a `database/mappings` directory. I went ahead and created those files/directories manually.

Still having issues... There are no Plastic related commands when running `php artisan` and running`$model->save()` throws an Exception: `Class plastic does not exist`

What am I missing?

**Comment by mfn** [comment]
> What am I missing?

Did you try this from the readme? This step is missing in your description:
> Then we need to add the plastic service provider to app/config.php under the providers key. Sleimanx2\Plastic\PlasticServiceProvider

As with any Laravel package, if you don't register the service provider, you'll get no functionality (even not being able to publish the configuration).

**Comment by zakiaziz** [comment]
@mfn d'oh! I was having a brain fart all day yesterday. That fixed my issue

@sleimanx2  Small issue: I think laravel looks for the directory `vendor/sleimanx2/plastic/src/resources` but it is named `vendor/sleimanx2/plastic/src/Resources` I get this error while running composer:
```
Can't locate path: </home/user/repo/vendor/sleimanx2/plastic/src/resources/config.php>
Can't locate path: </home/user/repo/vendor/sleimanx2/plastic/src/resources/database>
```
But renaming from `Resources` to `resources` fixed the issue

**Comment by sleimanx2** [comment]
thanks fixed in v0.2.0. @zakiaziz what OS are you using ?

**Comment by zakiaziz** [comment]
This was installed on Ubuntu 14.04

**Comment by vipinkaul123** [comment]
Some problem for install sleimanx2/plastic  search
I am trying thig code in my  Controller but not working
$result = Store::search()->match('name','Abrasives')->get();
 

BadMethodCallException in Builder.php line 2405:
Call to undefined method Illuminate\Database\Query\Builder::search()
