### ISSUE TITLE
Laravel 5.6 Support

### ISSUE THREAD

**Issue by abhi-cognitivo** [sleimanx2/plastic#142]
Hi,

I am having trouble with installing this package with Laravel 5.6. 

leimanx2/plastic v0.5.0 requires illuminate/console 5.2.*|5.3.*|5.4.*|5.5.* -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev], illuminate/console[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev].

Basically illuminate/console only goes up to 5.5, while we need 5.6 And I have also noticed that few days ago the code was updated to include 5.6, do you know when we can expect this to be on composer so as not to cause this error?

**Comment by jeversen** [comment]
Same question over here. Moved to laravel 5.6 but the version on packagist is not up to date with the github repo.

**Comment by abhi-cognitivo** [comment]
if you go to package finder you will notice that the current stable version is from last year. But there is a dev-master package that was updated on Feb 8th 2018. If you see the master branch from this repository you will notice that they have made the necesary changes, but it is still in dev phase. 

To access this, simple update your composer.json to:
"require": {
...
        "sleimanx2/plastic": "dev-master"
}

Then run composer update on your terminal. And presto you will have Plastic working with Laravel 5.6

**Comment by jeversen** [comment]
Indeed, this works 👍 

thanks !
