### ISSUE TITLE
Feature request: Disable automatically syncs model data for all models

### ISSUE THREAD

**Issue by approached** [sleimanx2/plastic#144]
Hi @ all

I'am working in a big project. Some developer don't work with elasticsearch. And our continuous integration - test process has not elasticsearch installed yet.

So me need to disable global all snycs in model. 
My workaround:
```php
    public $syncDocument;

    public function __construct(array $attributes = [])
    {
        $this->syncDocument = config('arena.elasticsearch_enable');
        parent::__construct($attributes);
    }
```

Has any a idea?

**Comment by sunkuet02** [comment]
@approached did you come out with a solution ?

**Comment by sunkuet02** [comment]
@sleimanx2 I think this issue should be solved.We are facing same.

**Comment by approached** [comment]
Not anymore interested for this package.

**Comment by sunkuet02** [comment]
@approached , did you find any better package for continuing on?

**Comment by approached** [comment]
I have my own script. But in next time i will try this: https://github.com/ErickTamayo/laravel-scout-elastic
