### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by jaystark** [sleimanx2/plastic#15]
While run the package installation it giving error - **NoNodesAvailableException in StaticNoPingConnectionPool.php line 51**  What is the best way to resolve this. Log contain the following data - 
log.WARNING: Curl exception encountered. [] []
log.WARNING: Request Failure: {"method":"GET","uri":"http://192.168.0.114:9200/plastic/books/_search","headers":{"host":["192.168.0.114:9200"]},"HTTP code":null,"duration":0.218,"error":"cURL error 7: Failed to connect to 192.168.0.114 port 9200: Connection refused"} []
log.WARNING: Response [null] []
log.WARNING: Marking node 192.168.0.114:9200 dead. [] []
log.WARNING: Retries left? true [] []
log.CRITICAL: No alive nodes found in cluster [] []

Is any solution for this. I am using windows 7 and laravel latest 5.2

**Comment by sleimanx2** [comment]
@jaystark you need to have at least one Elasticsearch instance running on 192.168.0.114 at port 9200
