### ISSUE TITLE
Custom index configuration

### ISSUE THREAD

**Issue by Metalrex100** [sleimanx2/plastic#153]
There is no information in docs how I can configure and create custom index with `sleimanx2/plastic`.

So, as `sleimanx2/plastic` is a wrapper over `elastic/elasticsearch-php` I can create console artisan command for index configuration and creation using `elastic/elasticsearch-php` package.

But it looks weird. Can I setup custom index with `sleimanx2/plastic`?

**Comment by sleimanx2** [comment]
currently plastic does not handle index creation, the way to do it is using the default client as you mentioned.
