### ISSUE TITLE
[Proposal] Move Maps to `App\Mappings` directory

### ISSUE THREAD

**Issue by HipsterJazzbo** [sleimanx2/plastic#18]
I was thinking that it might be a bit better to have the mappings saved within the `app` directory for a couple of reasons:

1. They're not really related to the database. I mean, I can see the logic but they don't seem to me to fit in the `database` directory.
2. They're pretty important to the functioning of the application. Seems like it'd be good to keep them with the rest of the application logic.

I'd be happy to prepare a PR if you think that this is a good idea.

:)

**Comment by sleimanx2** [comment]
Well I don't think that App\Mapping is a better place for Mappings for the following reasons:

1. Mappings are related to the database they are like indexes in the sql world.

2. I don't think that mappings are part of the application logic I consider them more or less as a database configuration, you won't use any of the mappings classes after you run them.

You can consider mappings are like migration for Elastic db.

What do you think ?
