### ISSUE TITLE
Integrate with Laravel Scout.

### ISSUE THREAD

**Issue by capitaladot** [sleimanx2/plastic#19]
https://laravel.com/docs/master/scout

**Comment by sleimanx2** [comment]
As far as I know scout only supports a search and a where method for searching and filtering your database.

for instance:

```php 
Book::search('pulp')->where('date',>,$minDate);
```

But plastic supports a wider array of elastic specific queries in addition to mapping.

Their is some similarities though like storing and updating documents on eloquent events.

I may need some time to get a clearer view , any suggestions ?

**Comment by HipsterJazzbo** [comment]
I'm not sure that integrating with Scout will be that useful. It's only for full-text searching, and there's already and elastic driver for it. I think Plastic is more for the advanced querying use cases, personally.

**Comment by HipsterJazzbo** [comment]
@sleimanx2 Now that I've had some time playing with both of these things, I wonder if it wouldn't actually be worth integrating into Scout? Maybe leverage Scout's code doing all the basic stuff, and just have the extra ability to do the advanced queries on top?

**Comment by mehrdaad** [comment]
@HipsterJazzbo are you suggesting to use plastic instead of scout?
