### ISSUE TITLE
does plastic work in Laravel 5.1?

### ISSUE THREAD

**Issue by krasho** [sleimanx2/plastic#23]
Hello.

I tried to install plastic in Laravel 5.1 and I got that errors:

Problem 1
    - Installation request for sleimanx2/plastic ^0.2.0 -> satisfiable by sleimanx2/plastic[v0.2.0].
    - Conclusion: remove laravel/framework v5.1.40
    - Conclusion: don't install laravel/framework v5.1.40
    - sleimanx2/plastic v0.2.0 requires illuminate/pagination 5.2.* -> satisfiable by illuminate/pagination[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/pagination v5.2.0|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.19|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.21|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.24|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.25|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.26|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.27|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.28|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.31|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.32|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.37|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.43|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.45|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.6|don't install laravel/framework v5.1.40
    - don't install illuminate/pagination v5.2.7|don't install laravel/framework v5.1.40
    - Installation request for laravel/framework == 5.1.40.0 -> satisfiable by laravel/framework[v5.1.40].

Thanks

**Comment by helloiamlukas** [comment]
You need to update to 5.2, Laravel 5.1 support has been removed [here](https://github.com/sleimanx2/plastic/commit/a8f2b763258a20b97d549856876c479223cfc519)

**Comment by sleimanx2** [comment]
it actually doesn't , however a pull request is always welcomed !

**Comment by adityachauhan053** [comment]
$result = Store::search()->match('name','Abrasives')->get();
i am trying this code in my controller but not working 

BadMethodCallException in Builder.php line 2405:
Call to undefined method Illuminate\Database\Query\Builder::search()
