### ISSUE TITLE
Why have to do bulk deleting from the relative model?

### ISSUE THREAD

**Issue by kevinzheng** [sleimanx2/plastic#27]
Thank you for the great work, it's the best for laravel with elasticsearch!
In the example, I should do like this to bulk delete documents:
`$author->document()->bulkDelete($author->books);`

But how can I just achieve this:
`$books = Books::all();
bulkDelete($books);`

Thank you!

**Comment by sleimanx2** [comment]
At the moment you can do something like this 

```php
$book = new Book();
Plastic::persist($book)->bulkDelete($book->all());
```
