### ISSUE TITLE
Bulk Indexing and GeoPoint

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#30]
Hey. I just came across this package, and it's exactly what I'm looking for ( Scout is not mature enough for what I need ). 

How can I batch index collections ? `$tag->document()->bulkSave($tag->books);` works if you pass it with a relationship. What if I have 100k items without any linking? 

Also, can I use Edge NGram Tokenizer with this?

Thanks in advance. Have a good one

**Comment by Melcus** [comment]
Managed to create the geopoint, created the index successfully. I hit the wall trying to import the data.
Created a console command that looks like this
```public function handle()
    {
        $min = $this->argument('min');
        $max = $min+5000;

        $this->processCompanies($min, $max);

        $min = $min + 5000;
        $this->info(memory_get_usage());
        unset($max);
        $this->call('command:SyncCompanies', ['min' => $min]);
    }


    protected function processCompanies($min, $max)
    {
        $companies = Company::where('id', '>', $min)->where('id', '<=', $max)->get();

        $companies->document()->bulkSave($companies);

        $this->info("Bulk indexed from {$min} to {$max}.");
    }```

What I get trying to run it is `[BadMethodCallException] Method document does not exist.`. Am I missing something?

**Comment by sleimanx2** [comment]
I updated the bulk statements documentation in v0.2.5 hope it is clearer :)

**Comment by Melcus** [comment]
Thanks for your response. That cleared the bulksave problem. Any news on NGram tokenizer?
