### ISSUE TITLE
mapper conflict with existing mapping in other types

### ISSUE THREAD

**Issue by hanjoyo** [sleimanx2/plastic#31]
Thank you for the great work. I have my initial fields mapping, but then I realized later I put on the wrong field. I tried to change the field mapping through php artisan mapping:run command, but got mapper conflict error message. How can I delete the initial mapping? How to change the mapped fields?

Please help me to solve this.

Here is the windows command prompt error message:

C:\xampp\htdocs\search>php artisan mapping:run
                                
  [Elasticsearch\Common\Exceptions\BadRequest400Exception] illegal_argument_exception: Mapper for [description] conflicts with existing mapping in other types:
[mapper [description] has different [store] values, mapper [description] has different [store_term_vector] values, mapper [description] has different [store_term_vector_offsets] values, mapper [description] has different [store_term_vector_positions] values]
                                                         
  [Elasticsearch\Common\Exceptions\BadRequest400Exception]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Mapper for [description] conflicts with existing mapping in other types:\n[mapper [description] has different [store] values, mapper [description] has different [store_term_vector] values, mapper [description] has different [store_term_vector_offsets] values, mapper [description] has different [store_term_vector_positions] values]"}],"type":"illegal_argument_exception","reason":"Mapper for [description] conflicts with existing mapping in other types:\n[mapper [description] has different [store] values, mapper [description] has different [store_term_vector] values, mapper [description] has different [store_term_vector_offsets] values, mapper [description] has different [store_term_vector_positions] values]"},"status":400}

Thank you.

**Comment by Melcus** [comment]
The way I did it is : 
Step 1. Delete the index ( I'm using https://github.com/royrusso/elasticsearch-HQ to manage indexes )
Step 2. Edit your mappings accordingly
Step 3. php artisan mapping:rerun
Step 4. Reimport your data

From ES documentation, in ES 2+ `existing type and field mappings cannot be updated` .

**Comment by hanjoyo** [comment]
thanx @Melcus, I have tried your solution. elasticsearch-HQ is very handy for monitoring and managing the elasticsearch instances and clusters. However I run into another problem: No alive nodes found in your cluster.
