### ISSUE TITLE
Models should be in separate indices

### ISSUE THREAD

**Issue by HipsterJazzbo** [sleimanx2/plastic#34]
According to [this page](https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html), one shouldn't mix different types of data in a single index. By default, Plastic stores all models in a single index, and differentiates based on type.

However, the underlying Lucene instance flattens out all mappings, causing conflict issues like #31. I have also started to run into issues like this.

Totally understanding how big a change this would be, I reckon we should think about changing this package to use separate indices for each model type by default. I'd be happy to tackle the work and open a PR.

Thoughts?

**Comment by tobias-kuendig** [comment]
This is exactly the problem I tried to solve with the `inIndex` method that was added to the search builder and persistance layer.

According to [this page](https://www.elastic.co/blog/index-vs-type) it depends highly on your use case whether or not you should store every model in a different index or use types instead.

I suggest adding something like an `elasticIndex` property to every model that allows you to overwrite the default index specified in the config on a per model basis.

With the `inIndex` methods in place (after merge of PR #33) this shouldn't be too complicated to accomplish.

**Comment by HipsterJazzbo** [comment]
Yeah. I still think though, that for eloquent models in particular, each should be in it's own index *by default*. That could probably happen in the EloquentPersistence class and a few other places.

**Comment by sleimanx2** [comment]
Done in v0.2.5 , also added custom index for suggestion and mapping
