### ISSUE TITLE
->must()->term('name','kimchy')  not working at all

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#35]
Trying to match something and it doesn't give any results. Is this an issue someone else is experiencing ?

**Comment by sleimanx2** [comment]
This is not a package issue you can use `toDSL` instead of `get` to debug your query.

**Comment by Melcus** [comment]
Thanks for your response.  My `toDSL` looks like this http://i.imgur.com/a4LcmGn.png , the data is in there, double checked, yet the response is non existent.
