### ISSUE TITLE
How to create index, migrate data with console command?

### ISSUE THREAD

**Issue by amelkikh** [sleimanx2/plastic#36]

**Comment by Melcus** [comment]
The way I did it is :
`php artisan make:command IndexModel`

in it, changed `protected $signature = 'command:ImportModelToES {min}';`

The handle method looks like this : 
```
public function handle()
    {
        $min = $this->argument('min');
        $max = $min+5000; //batch size
        $this->processModel($min, $max);
        $min = $min+5000; // these must match
        $this->info(memory_get_usage());
        unset($max);
        $this->call('command:ImportModelToES', ['min' => $min]);
    }

    protected function processModel($min, $max)
    {

        $models = Model::where('id', '>', $min)->where('id', '<=', $max)->get();

        Plastic::persist()->bulkSave($models);
        $this->info("Indexed to ES  from {min} to {max}.");

    }
```

Then you just call `php artisan command:ImportModelToES 1' . I did it this way because of my requirements but there are more elegant ways to do it. Look at `chunk` in laravel documentation

**Comment by amelkikh** [comment]
Is it required to create index manually or how to create index "on fly" if it does not exist?

**Comment by Melcus** [comment]
I would suggest you create the indices manually, as you can specify the shards, replicas or other settings.
You can use https://github.com/royrusso/elasticsearch-HQ to create indices or https://github.com/lmenezes/elasticsearch-kopf

**Comment by amelkikh** [comment]
Already use elasticsearch-HQ but how you see this in production?
In production usually needs to create some kinds of deployment commands, no possibility to use GUI and I'm really hate to use different stupid scripts to do this important things

**Comment by Melcus** [comment]
You just create the index on your production server ( with HQ or command), you do it once anyway. You specify the index in your plastic.php file, and that's it. No more configurations.

**Comment by sleimanx2** [comment]
You can create and delete indexes as follows 

```php
Plastic::getClient()->indices()->delete(['index' => Plastic::getDefaultIndex()]);

Plastic::getClient()->indices()->create(['index' => Plastic::getDefaultIndex()]);
```

added this section to documentation ...

**Comment by amelkikh** [comment]
Thanks a lot. I think that need to add this code examples into readme
