### ISSUE TITLE
How to use the scroll api?

### ISSUE THREAD

**Issue by RpCoding** [sleimanx2/plastic#38]
I need an example of how to use the scroll API with plastic if possible.

Docs: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html#search-request-scroll

Thanks in advance.

**Comment by sleimanx2** [comment]
I don't think we have it implemented but you can always use ```$client = Plastic::getClient();``` to reach the official elastic php client.
