### ISSUE TITLE
EloquentFiller::isMultiLevelArray() must be of the type array

### ISSUE THREAD

**Issue by xjqxz2** [sleimanx2/plastic#42]
Hello , I did a search for Elasticsearch, but reported this error, what can I do?

> [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Type error: Argument 1 passed to Sleimanx2\Plastic\Fillers\EloquentFiller::isMultiLevelArray() must be of the type array, integer given, called in /vendor/sleimanx2/plastic/src/Fillers/EloquentFiller.php on line 123

The query is as follows:

`UserModel::search()->match('user_name', 'admin')->get()
`

toDSL
```
array:1 [
  "query" => array:1 [
    "match" => array:1 [
      "user_name" => array:1 [
        "query" => "admin"
      ]
    ]
  ]
]
```

**Comment by dukmaurice** [comment]
Same issue, I just add an other control in EloquentFilter.php line 118 :

`if (!is_array($value) || $value === null) `

instead of : 

`if ($value === null) {`

Maybe because I have a custom buildDocument function with relation : 

`public function buildDocument()
    {
        return [
            "created_at" => $this->created_at->toDateTimeString(),
            "uuid" => $this->uuid,
            "address" => $this->address,
            'imei' => $this->imei,
            'checkresult' => $this->checkresult,
            "type" => $this->type->code.' - '.$this->type->name
        ];
    }`
It's ok now (I think) :)

**Comment by sleimanx2** [comment]
The thing is that if the function reaches `isMultiLevelArray ` it means that the current value is ```instanceof Relation``` and for that reason the value can only be an array. 

@dukmaurice do you have a method `type` that returns a relation in your model ?

**Comment by xjqxz2** [comment]
I debug my program with dd() output $value But it is not an array, is a string, because isMultiLevelArray limited to receive array, so reported this error.

**Comment by sleimanx2** [comment]
@xjqxz2 yes but if isMultiLevelArray receives a string it means that there is something wrong with the setup can you share the model that is facing this issue ?

**Comment by ellisio** [comment]
Kind of late, but I want to shed light on this. If you have the following in your model:

```php
public function author()
{
     return $this->belongsTo(Author::class);
}
```

Then you configure `buildDocument()` like so:

```php
public function buildDocument()
{
    return [
        'id' => $this->id,
        'title' => $this->title,
        'author' => 'Tom Clancy',
    ];
}
```

This will throw this error. This is because the `$value` is "Tom Clancy" when it is being passed to this method. The reason this error happens is because the `$relation` set by finding the `author()` on the `Book` class.

To fix this you need to change `buildDocument()` to this:

```php
public function buildDocument()
{
    return [
        'id' => $this->id,
        'title' => $this->title,
        'author' => $this->author,
    ];
}
```
