### ISSUE TITLE
Eager Loading

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#43]
Is there a way to achieve this at the moment?

**Comment by sleimanx2** [comment]
at the moment you can store the model relation that you want to always eager load in your elastic document.

for instance in this example the images will always be eager loaded when hitting elasticsearch ... 
```php
public $searchable = ['id', 'name', 'body', 'tags', 'images'];
```

**Comment by jamesgraham** [comment]
@sleimanx2 does this support eager loading from dependent models

i.e. if I had:

PostModel (with Searchable trait)
public $searchable = ['id', 'name', 'user'];

UserModel
public $visible = ['id', 'name', 'team'];

TeamModel
public $visible = ['id', 'name'];


Should the team object appear under the user?
