### ISSUE TITLE
"type" is not a valid parameter. 

### ISSUE THREAD

**Issue by Damian89** [sleimanx2/plastic#45]
Do you have an idea how to resolve this issue:

```
UnexpectedValueException in AbstractEndpoint.php line 247:
"type" is not a valid parameter. Allowed parameters are: "analyzer", "analyze_wildcard", "default_operator", "df", "explain", "fields", "fielddata_fields", "filter_path", "from", "ignore_unavailable", "allow_no_indices", "expand_wildcards", "indices_boost", "lenient", "lowercase_expanded_terms", "preference", "q", "query_cache", "request_cache", "routing", "scroll", "search_type", "size", "sort", "source", "_source", "_source_exclude", "_source_include", "terminate_after", "stats", "suggest_field", "suggest_mode", "suggest_size", "suggest_text", "timeout", "track_scores", "version", "request_cache", "client", "custom", "filter_path"
```

Using CURL I see that my server has entries, which are automatically placed via Plastic, but I cant read/search them using this simple example:

```
$search = $request->input('search');
$results = Plastic::search()->match('title',$search)->get();
```

The error is very obvious - replacing:

```
    public function getType()
    {
        return $this->type;
    }
```

with:

```
    public function getType()
    {
         return 'searchindex'; // my type
    }

```
works well, but thats not nice. 

Looks like I forgot about something? Do you have an idea?

**Comment by Damian89** [comment]
Digging in your code, I got it working:

`$results = Plastic::search()->type('searchindex')->match('title', $search)->get();`
OR
`$results = Plastic::search()->model( new Searchindex )->match('title', $search)->get();`

But hits(), maxScore(), ... do not work in $result. 

Any other ideas why type, index, ... are not being passed to Plastic?

**Comment by Melcus** [comment]
Why are you not searching by model? 

`$results = Model::search()->match('title', $search)->get()`

**Comment by Damian89** [comment]
Lol, because I'm an idiot... thanks for the hint! *selfshame

**Comment by Melcus** [comment]
Np, glad I could help
