### ISSUE TITLE
query_parsing_exception: failed to find geo_point field [location]

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#46]
On model I have 
` 'location' => ['lat' => $this->lat, 'lon' => $this->lng ],`

In mapping
` $map->point('location')->lat_long(true)->geohash(true);`

It's being saved on ES http://i.imgur.com/V8FKtXS.png

Tried in kibana if I can build a Tile map, but, `No Compatible Fields: The "XXXXX" index pattern does not contain any of the following field types: geo_point`  

Any ideas?

**Comment by Melcus** [comment]
I recreated the index manually setting the mapping


```
  "location": {
          "geohash": true,
          "type": "geo_point"
```

works now

**Comment by sleimanx2** [comment]
You can set the field type when you create your mappings, you can avoid doing it manually right ?

**Comment by Melcus** [comment]
I did set it, as I pointed out in my problem. It just didn't recognise it as a geo point

**Comment by sleimanx2** [comment]
I see , and you didn't get any error when you ran the mappings ?

**Comment by Melcus** [comment]
Nop, the data was being saved just not identified as a geo point
