### ISSUE TITLE
is it possible to use auto-generate id by elasticsearch?

### ISSUE THREAD

**Issue by longthanhtran** [sleimanx2/plastic#49]
Per [elastico document](https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing), they advise to use auto generate id so is it possible to keep model id (db id) inside each document while leave the "_id" field to elasticsearch to decide? Thanks (below is a sample)

```json
...
         {
            "_index": "sample",
            "_type": "user",
            "_id": "2",
            "_score": 1,
            "_source": {
               "first_name": "E",
               "last_name": "F",
               "id": 2
            }
         },
         {
            "_index": "sample",
            "_type": "user",
            "_id": "AVlm__uB9pLpNbCey5qK",
            "_score": 1,
            "_source": {
               "first_name": "A",
               "last_name": "B",
               "id": 3
            }
         },
...
```

**Comment by ellisio** [comment]
The problem with this is when it comes to saving, updating, and deleting individual records. Looking through the source code of Plastic it appears it relies on the local model ID to perform it's tasks:

https://github.com/sleimanx2/plastic/blob/master/src/Persistence/EloquentPersistence.php#L84
https://github.com/sleimanx2/plastic/blob/master/src/Persistence/EloquentPersistence.php#L111
https://github.com/sleimanx2/plastic/blob/master/src/Persistence/EloquentPersistence.php#L132
https://github.com/sleimanx2/plastic/blob/master/src/Persistence/EloquentPersistence.php#L163
https://github.com/sleimanx2/plastic/blob/master/src/Persistence/EloquentPersistence.php#L192

**Comment by longthanhtran** [comment]
ic, so I think there will be many changes required just in order to implement this. Hopefully we consider to implement in the future :) thanks @ellisio

**Comment by sleimanx2** [comment]
@longthanhtran can you tell me about the use case where you want to have the id from Elasticsearch instead of the Model ?

**Comment by longthanhtran** [comment]
hi @sleimanx2, I have a project with few mil of documents, for now, to store on es and per es advice, I want to know if can use self-generate id for es documents. I think model id still store within document while let es manage it "_id" to achieve performance benefit. :)

**Comment by sleimanx2** [comment]
The Auto-ID optimization is removed In elastic v2 check it out https://www.elastic.co/blog/performance-indexing-2-0
