### ISSUE TITLE
ES 5.1?

### ISSUE THREAD

**Issue by ellisio** [sleimanx2/plastic#51]
Seeing as how this is still under active development, have you thought about making sure this is built against the latest ES 5.1?

Upgrading `composer.json` to the following:

```
"elasticsearch/elasticsearch": "~5.1",
"ongr/elasticsearch-dsl": "dev-master"
```

Then running your unit tests results in a full pass. I know you probably don't want `dev-master` as dependency right now. But being under active development can't hurt to do so seeing as how `ongr/elasticsearch-dsl` is actively working on releasing their `5.x` support.

```
$ vendor/bin/phpunit
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.0.14 with Xdebug 2.5.0
Configuration:	/Users/andrew/Developer/GitHub/ellisio/plastic/phpunit.xml

...............................................................  63 / 141 ( 44%)
............................................................... 126 / 141 ( 89%)
...............

Time: 2.72 seconds, Memory: 18.00MB

OK (141 tests, 246 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done
```

**Comment by sleimanx2** [comment]
perfect added a develop branch for ES 5 support

**Comment by ellisio** [comment]
I think this needs to be reopened and discussed a little more.

Right now you're wanting to include support for Laravel `5.2.*|5.3.*`. Well, `5.4.*` is now a thing.

Also, the underlying library of `elasticsearch/elasticsearch` is going to require PHP `^7.0` as they require `ext-json >= 1.3.7`. PHP `5.6.x` ships with `ext-json 1.2.1`.

So if we want to support the `elasticsearch/elasticsearch 5.x` the minimum PHP version Plastic will need to support is `7.0`. This cuts out all current Laravel versions as the framework only requires `5.6.4+`.

Laravel 5.5 will require PHP `7.0+`. So until Laravel requires 7.0 I would halt development and support on ES 5.

**Comment by jamesgraham** [comment]
@ellisio I understand where you come from but what solution can we arrive at for people running PHP7 and wanting ES 5? Should we have a new major version of this library for these latest versions?

**Comment by ellisio** [comment]
So after some discussion with the `elasticsearch/elasticsearch` author, he was willing to add a new library to the class to help out our cause of keeping support for `5.x`. Take a look:

https://github.com/elastic/elasticsearch-php/issues/534#issuecomment-277246228

**Comment by jamesgraham** [comment]
@ellisio how should we use this now?

**Comment by jamesgraham** [comment]
@sleimanx2 @ellisio The ES library has been updated to 5.1.3 to support this - what are the next steps?

**Comment by dreferreira** [comment]
@ellisio @sleimanx2 any further update on how to get this to be compatible with ES 5.X?? I'm currently working on a large project involving laravel 5.4 with PHP 7.0.2 (Which is required for some of the processing within laravel) and would like to require this package with the latest ES.

**Comment by dominicmomentum** [comment]
@ellisio @sleimanx2 I'm also very interested having this package compatible with ES 5.X and PHP 7. Could we create a separate branch for that until Laravel 5.5 in July?

**Comment by sleimanx2** [comment]
the issue is that the test are not green anymore due to the following update

```
Since Elasticsearch 5.0 the support for top level filters was dropped. The same functionality is now supported via BoolQuery
```

I'll work on fixing the issue soon.

**Comment by HipsterJazzbo** [comment]
@sleimanx2 What needs doing on this? Is the work on the develop branch current, or is it out of date? I note that it is currently 32 commits behind master.

**Comment by hoersten** [comment]
@sleimanx2 Any updates on this?  We'd like to use it on our Laravel 5.4, ES 5.4 and PHP 7 site.

**Comment by jamesgraham** [comment]
Hey @sleimanx2 is there anything the community can do to help move this?

**Comment by sleimanx2** [comment]
Please check v0.5.0 🥂
