### ISSUE TITLE
preserve_position_increments Completion mapping

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#52]
My mapping is
```$map->completion('company_name_suggest',['analyzer' => 'simple', 'search_analyzer'=>'simple', 'preserve_position_increments' => 'false']);```

but the `preserve_position_increments` remains true. Any suggestions ?

**Comment by sleimanx2** [comment]
No can you follow the cause issue ?

**Comment by Melcus** [comment]
I haven't really been able to find the cause .. would really appreciate if you take a look

**Comment by sleimanx2** [comment]
will try to ...
