### ISSUE TITLE
Relations search

### ISSUE THREAD

**Issue by belov91** [sleimanx2/plastic#58]
I want to use plastic to search in model that has the following structure:

```
Activity (Model)
User (Model)
Category (Model)
```

one User can have many Activity.
I am using MySQL for DB.

I want to use the Searchable trait (elasticsearch) only in the Activity model, but in the same time to be able to make queries like: 

`get all activities where the user's name is joe.`

Also when the user is updated it should update the index for the Activity.

Is this even possible and if yes how?

Also if someone has better idea of how to develop this I am open for proposals. :slightly_smiling_face: 

@jamesgraham

**Comment by mschreck** [comment]
You can just normalize your data on index time using the buildDocument method:

```
class Activity {

    use Searchable;

    public function buildDocument()
    {
        return $this->load('user')->toArray();
    }

    public function user()
    {
        return $this->hasOne('App\User');
    }
}
```

Then your document in elastic will look like:

```
{
  id: 1,
  name: "My activity",
  user: {
    id: 1,
    name: "joe",
    email: "joe@example.com"
    ...
  }
}
```

and you can search like this:
`Activity::search()->filter()->term('user.name', 'joe');`


I would use a nested document for users, so you have to adjust your mapping:
```
$map->nested('user', function (Blueprint $map) {
    $map->string('id');
    $map->string('name');
    $map->string('email');
});
```

Query will then look like
```
Activity::search()->nested('sources', function (SearchBuilder $builder) use ($term) {
    $builder->match('sources.contract_type', $term);
});
```

**Comment by belov91** [comment]
Hi @mschreck and thanks for the answer.

The first part is working perfect.

I`ve decided to try with the nested query and mapping but it isn't working. 

Is there anything special that I should do when I want to use the nested queries?

**Comment by sleimanx2** [comment]
@belov91 nested queries needs special mappings for instance in your Activity model mapping you need something like this.

```php
$map->nested('user', function (Blueprint $blueprint) {
              
   $blueprint->integer('id');

   $blueprint->string('name', [
          'store'    => 'true',
          'index'    => 'analyzed',
          'analyzer' => 'english',
    ]);

    //...
});
```

ll reopen the issue if needed
