### ISSUE TITLE
Standard analyzer not "analyzing"

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#59]
Mapping is
`$map->completion('title_suggest',['analyzer' => 'standard']);`

My string is `Verkäufer` and I would expect the analyzer to remove the `ä` but it does not. 

In es, 
![ES](http://i.imgur.com/ZLwbZpS.png)

Is this a package bug or I missed something ?

**Comment by Melcus** [comment]
A workaround I found for this is to create another field manually and replace the special characters. If anyone finds this helpful [https://gist.github.com/Melcus/220054538c7c3e542f8611ae1abd7e49]: The function

**Comment by sleimanx2** [comment]
are you sure its the issue is from the package ?

**Comment by sleimanx2** [comment]
will reopen upon update ...
