### ISSUE TITLE
Publishing assets by provider fails.

### ISSUE THREAD

**Issue by capitaladot** [sleimanx2/plastic#6]
php artisan vendor:publish --provider="Sleimanx2\Plastic\PlasticServiceProvider"
Can't locate path: <_{my project root}_/vendor/sleimanx2/plastic/src/resources/config.php>
Can't locate path: <_{my project root}_/vendor/sleimanx2/plastic/src/resources/database>
Publishing complete for tag []!

**Comment by sleimanx2** [comment]
I don't seem to reconstruct the bug , does those files/directory actually exists in your vendor directory ?

**Comment by capitaladot** [comment]
Thanks for the quick response.
Indeed, they are there.

**Comment by sleimanx2** [comment]
what OS are you using , did you try in Homestead ?

**Comment by capitaladot** [comment]
Ubuntu 14.04. No, not in Homestead.
Other packages' vendor:publish commands have worked for me with "--provider" specified.
I am using this flag because I have at least one package the overwrites views in public if re-published.

**Comment by sleimanx2** [comment]
I've tried it on macOS and ubuntu 14.04 it works fine , I'm on v0.1.2. Could be some permission issue ?
