### ISSUE TITLE
excludes and highlights

### ISSUE THREAD

**Issue by XavRsl** [sleimanx2/plastic#68]
Hi !
First of all, thank you for this package, it's very handy.
I'm trying to exclude some fields from my search results. I just don't want my users to be able to see the IDs of the resources. If I was to use simple Json I would do the following :
```
"_source": {
    "excludes": [ "*.id" ]
},
```
Easy enough. But I can't figure out how to do it with plastic.
Same thing for Highlight, I see that ElasticsearchDSL package has an Highlight Endpoint, but would it be possible to use that with plastic ?

Thanks.

Xavier

**Comment by sleimanx2** [comment]
hey @XavRsl , unfortunately its not available at the moment, it think its easy to add the Highlight Endpoint to the SearchBuilder a PR is much appreciated.

**Comment by XavRsl** [comment]
Thank you for the answer.

Xavier
