### ISSUE TITLE
Fielddata is disabled on text fields by default

### ISSUE THREAD

**Issue by phuongnm153** [sleimanx2/plastic#69]
When I using this code:
`$books = Book::search()
    ->multiMatch(['title', 'description'], 'ham on rye', ['fuzziness' => 'AUTO'])
    ->sortBy('date')
    ->paginate();`
I give a error: Fielddata is disabled on text fields by default.
Can you help me to set fielddata=true

**Comment by t1k3hu** [comment]
mappings/app_models_book@map
```
...
Map::create($this->getModelType(),function(Blueprint $map){
    $map->date('date', [
        'fielddata' => true,
        'format'    => 'yyyy-MM-dd HH:mm:ss'
    ]);
},$this->getModelIndex());
```

```
$ php artisan mapping:rerun
```

**Comment by phuongnm153** [comment]
Thanks. Its working for me

**Comment by phuongnm153** [comment]
So i have a new issue.
I have a "updated_at" field is date type. When I run the command 
` php artisan mapping:run`
Then It show a message:
"Can't merge a non object mapping [updated_at] with an object mapping [updated_at]"
can u help me?

**Comment by t1k3hu** [comment]
Just a tip but I think this is the solution.
```
$ curl -XDELETE "http://localhost:9200/plastic"
$ curl -XPUT "http://localhost:9200/plastic"
$ php artisan mapping:run
```

**Comment by phuongnm153** [comment]
Thanks. I got it
