### ISSUE TITLE
How do I setting for custom analyzers?

### ISSUE THREAD

**Issue by phuongnm153** [sleimanx2/plastic#72]
Hi. I'm newbie.
I found anything in readme, so I cant find anyway to custom analyzers for my index.
Can u help me?
Example, I want to have a custom analyzers bellow:
`"analyzer": {
              "did_you_mean": {
                  "filter": ["lowercase"],
                  "char_filter": ["html_strip"],
                  "type": "custom",
                  "tokenizer": "vi_tokenizer"
              },
              "autocomplete": {
                  "filter": ["lowercase", "autocomplete_filter"],
                  "char_filter": ["html_strip"],
                  "type": "custom",
                  "tokenizer": "standard"
              },
              "default": {
                  "filter": ["lowercase", "stopwords_filter", "stemmer_filter"],
                  "char_filter": ["html_strip"],
                  "type": "custom",
                  "tokenizer": "standard"
              }
          }`
Thanks for help.

**Comment by t1k3hu** [comment]
Did you mean?
```
curl -XPUT "http://localhost:9200/plastic" -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "did_you_mean": {
          "type":      "custom",
          "tokenizer": "standard",
          "filter": [
            "standard",
            "lowercase",
            "asciifolding",
            "edge_ngram"
          ]
        }
      }
    }
  }
}'
```

**Comment by phuongnm153** [comment]
So I use a library custom analyzer "vi_tokenizer" in here: https://github.com/duydo/elasticsearch-analysis-vietnamese.
But It show a message : "Failed to find vi_tokenizer".
I have installed this plugin by a command "bin/elasticsearch-plugin install".
Can u help me the solution?
Thanks

**Comment by t1k3hu** [comment]
Just follow the [Installation](https://github.com/duydo/elasticsearch-analysis-vietnamese#installation-on-elasticsearch-5x) section and use analyzer in application.

```
$map->string('title', [
    'analyzed' => true,
    'analyzer' => 'vi_analyzer'
]);
```
