### ISSUE TITLE
Perform "foreach" in received content

### ISSUE THREAD

**Issue by luizguilhermefr** [sleimanx2/plastic#73]
Hi. How would I correctly perform a `foreach` into received `data` array?

My query currently is like

```
$result = User::search()
            ->multiMatch(['name', 'last_name'], $query, ['fuzziness' => 'AUTO'])
            ->paginate(16);
```

I want to change some variable names before returning it. When I try to perform a `foreach` I receive `Undefined property: Sleimanx2\Plastic\PlasticPaginator::$data`.

**Comment by hacheme** [comment]
Hi, I have the same problem

**Comment by hacheme** [comment]
public function index(Request $request)
    {
        if($query = Input::get('query', false))
        {

                $books = Afica::search()
                    ->multiMatch(['name','city_hotel'], $query, ['fuzziness' => 'AUTO'])
                    ->paginate(26);
       

                $afica = Afica::search()
                    ->should()
                    ->match('name',$query)
                    ->paginate(26);
   
         }
         
        else 
        {
               $books = Afica::search()
            ->paginate(26);
   
           $afica = Afica::search()
            ->paginate(26);
        
        }
        if ($request->ajax())
        {
                return view('presult', compact('books','afica'));
        }
        return view('welcome',compact('books','afica'))->render(); 

        
    }

@foreach($books as $Afica)

            <article class="one-third">
              <figure><a href="#" title=""><img src="{{{ $Afica->photo_url }}}" alt="" style="height: 215px!important;" /></a></figure>

              <div class="details">
           
                <h3>{{{ $Afica->name }}}
                  <span class="stars">
                 
                      <?php 

                      for ($i=1 ; $i<=$Afica->class ; $i++) 
                      {
                      echo ' <i class="material-icons">&#xE838;</i>';
                      }
                  
                  ?>
                  </span>
                </h3>
                <span class="address">{{{ $Afica->city_hotel }}},{{{ $Afica->address }}}  <a href="">Show on map</a></span>
                <span class="rating">{{{ $Afica->preferred }}}</span>
                <span class="price">Max rate  <em>$ {{{ $Afica->maxrate }}}</em> </span>
                <span class="pricee">Min rate  <em>$ {{{ $Afica->minrate }}}</em> </span>
                <div class="description">
                  <p>{{{ $Afica->desc_en }}}<a href="hotel?query={{{ $Afica->name }}}">More info</a></p>
                </div>   
                <a href="{{{ $Afica->hotel_url }}}" title="Book now" class="gradient-button">Book now</a>
              </div>
            </article><?php $myArray[] = $Afica->id;?>

            
            @endforeach

           @endif

**Comment by hacheme** [comment]
test this

**Comment by sleimanx2** [comment]
you should call the result method ```$result->result()```
