### ISSUE TITLE
Undefined property: Sleimanx2\Plastic\PlasticPaginator::$photo_url

### ISSUE THREAD

**Issue by hacheme** [sleimanx2/plastic#74]
$brans = request()->priceFilter;
       
    if(!empty($brans) && !empty($query))
        {

                 $product = "";
             foreach($brans  as $data){
               $minMax = explode("-",$data);
               
           
              $product[] = Afica::search()
                    ->multiMatch(['name','city_hotel'], $query, ['fuzziness' => 'AUTO'])
                    ->filter()
                    ->range('minrate',['from'=>$minMax[0],'to'=>$minMax[1]])
                    ->paginate(25);
                       
   
         }
          $books = $product;
          
     }
         return view('welcome',compact('books'));

I want when I click on one of the checkboxs it gives me the list of hotels whose price is between 0-49, I do the following function, it works perfectly but I have an error
In the view 
@foreach($books as $Afica)

            <article class="one-third">
              <figure><a href="#" title=""><img src="{{{ $Afica->photo_url }}}" alt="" style="height: 215px!important;" /></a></figure>

              <div class="details">
           
                <h3>{{{ $Afica->name }}}
                  <span class="stars">
                 
                      <?php 

                      for ($i=1 ; $i<=$Afica->class ; $i++) 
                      {
                      echo ' <i class="material-icons">&#xE838;</i>';
                      }
                  
                  ?>
                  </span>
                </h3>
                <span class="address">{{{ $Afica->city_hotel }}},{{{ $Afica->address }}}  <a href="">Show on map</a></span>
                <span class="rating">{{{ $Afica->preferred }}}</span>
                <span class="price">Max rate  <em>$ {{{ $Afica->maxrate }}}</em> </span>
                <span class="pricee">Min rate  <em>$ {{{ $Afica->minrate }}}</em> </span>
                <div class="description">
                  <p>{{{ $Afica->desc_en }}}<a href="hotel?query={{{ $Afica->name }}}">More info</a></p>
                </div>   
                <a href="{{{ $Afica->hotel_url }}}" title="Book now" class="gradient-button">Book now</a>
              </div>
            </article><?php $myArray[] = $Afica->id;?>

            
            @endforeach

           @endif

**Comment by sleimanx2** [comment]
i think you missed to call the result method.

```
Afica::search()
->multiMatch(['name','city_hotel'], $query, ['fuzziness' => 'AUTO'])
->filter()
->range('minrate',['from'=>$minMax[0],'to'=>$minMax[1]])
->paginate(25)
->result();
```
