### ISSUE TITLE
Nesting boolean filters

### ISSUE THREAD

**Issue by jamesgraham** [sleimanx2/plastic#76]
Hi,

How do I achieve this https://www.elastic.co/guide/en/elasticsearch/guide/current/combining-filters.html#_nesting_boolean_queries

I want to have a filter similar to SQL:

WHERE
    foo = bar
    AND (
        (a = b) OR (c = d)
    )

It seems to require an additional bool query but I cannot see how to insert that?

**Comment by sleimanx2** [comment]
I think you can achieve it through nested queries https://github.com/sleimanx2/plastic#nested-query. using ```$query->toDSL() ``` instead of ```$query->get()``` could help you debug the output ...
