### ISSUE TITLE
How to configure for REST to ES on AWS?

### ISSUE THREAD

**Issue by capitaladot** [sleimanx2/plastic#8]
Placing my ES AWS instance endpoint (with port 80) in the hosts array of plastic php and running 
`php artisan mapping:run`
results in: 

>   [Elasticsearch\Common\Exceptions\Missing404Exception]              
>   {"error":"IndexMissingException[[plastic] missing]","status":404} 

Is this a supported use case, or am I just doing it wrong?

**Comment by luizguilhermefr** [comment]
Please, how did you fixed this, @capitaladot ?

**Comment by sleimanx2** [comment]
this isn't an AWS issue it clearly indicates that the index plastic is not created

**Comment by luizguilhermefr** [comment]
No, I found out the problem was with the core of plastic: elasticsearch-php
that enforces port 9200 if none specified.

After a lot of time, I set up with port 443 (ssl default) and it did the
trick.

Em sex, 6 de abr de 2018 09:30, Sleiman Sleiman <notifications@github.com>
escreveu:
