### ISSUE TITLE
Pausing indexing

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#81]
I recently bumped into a problem. I have to go through a model and update some fields. With every save, it will call the ES server to update, and it will slow things dramatically. Is there a way to pause the indexing for specific block of operations ? 

I noticed  something similar in Laravel Scout : https://laravel.com/docs/5.4/scout#pausing-indexing

App\Order::withoutSyncingToSearch(function () {
    // Perform model actions...
});

Thanks in advance !

**Comment by mschreck** [comment]
Hi,

you can set public property $syncDocument to false on your model:

public $syncDocument = false;

**Comment by sleimanx2** [comment]
as @mschreck indicated the only available way at the moment is to toggle the syncDocument key on your model ```$model->syncDocument = false```
