### ISSUE TITLE
Invalid namespaces for SearchBuilder

### ISSUE THREAD

**Issue by mbm-rafal** [sleimanx2/plastic#83]
I'm using dev-develop version.

Regarding to https://github.com/ongr-io/ElasticsearchDSL/tree/5.x/src/Query
There are invalid namespaces in: https://github.com/sleimanx2/plastic/blob/develop/src/DSL/SearchBuilder.php

**Comment by sleimanx2** [comment]
Fixed however the test are not passing anymore due to the following:
`Since Elasticsearch 5.0 the support for top level filters was dropped. The same functionality is now supported via BoolQuery`
