### ISSUE TITLE
split filter into new bool

### ISSUE THREAD

**Issue by nmkr** [sleimanx2/plastic#89]
Hello,

How can i solve this query:

`
{

    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "name": {
                            "query": "cafe"
                        }
                    }
                }
            ],
            "filter": [
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "city": "searchparam"
                                }
                            },
                            {
                                "term": {
                                    "city": "searchparam"
                                }
                            },
                            {
                                "term": {
                                    "category_secondary": "searchparam"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "sort": [
        {
            "listing_level": {
                "order": "desc"
            }
        }
    ]

}
`

into the following syntax? i want to split the filter out otherwise the filter show not the expected results

`
{

    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "name": {
                            "query": "cafe"
                        }
                    }
                }
            ],
            "filter": [
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "city": "searchparam"
                                }
                            },
                            {
                                "term": {
                                    "city": "searchparam"
                                }
                            }
                        ]
                    }
                }
            ],
            "filter": [
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "category_secondary": "searchparam"
                                }
                            }
                        ]
                    }
                }
            ]            
        }
    },
    "sort": [
        {
            "listing_level": {
                "order": "desc"
            }
        }
    ]

}
`

thanks and regards :-)

**Comment by sleimanx2** [comment]
solved in v0.5.0
