### ISSUE TITLE
Trait creation event throws "invalid request body provided" InvalidArgumentException from Guzzle

### ISSUE THREAD

**Issue by capitaladot** [sleimanx2/plastic#9]
ERROR: exception 'InvalidArgumentException' with message 'Invalid request body provided' in _{project path}_vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:289 Stack trace: #0 _{project path}_vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(248): GuzzleHttp\Ring\Client\CurlFactory->addStreamingBody(Array, Array) #1 _{project path}_vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(203): GuzzleHttp\Ring\Client\CurlFactory->applyBody(Array, Array) #2 _{project path}_vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(30): GuzzleHttp\Ring\Client\CurlFactory->applyMethod(Array, Array) #3 _{project path}_vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(84): GuzzleHttp\Ring\Client\CurlFactory->__invoke(Array, Resource id #920) #4 _{project path}_vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array) #5 _{project path}_vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array) #6 _{project path}_vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(184): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array) #7 _{project path}_vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(159): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array) #8 _{project path}_vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest('PUT', '/plastic/descri...', Array, Array, Array, Object(Elasticsearch\Transport)) #9 _{project path}_vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(80): Elasticsearch\Transport->performRequest('PUT', '/plastic/descri...', Array, Array, Array) #10 _{project path}_vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(911): Elasticsearch\Endpoints\AbstractEndpoint->performRequest() #11 _{project path}_vendor/sleimanx2/plastic/src/Connection.php(148): Elasticsearch\Client->index(Array) #12 _{project path}_vendor/sleimanx2/plastic/src/Persistence/EloquentPersistence.php(27): Sleimanx2\Plastic\Connection->indexStatement(Array) #13 _{project path}_vendor/sleimanx2/plastic/src/Searchable.php(40): Sleimanx2\Plastic\Persistence\EloquentPersistence->save() #14 [internal function]: App\Description::Sleimanx2\Plastic\{closure}(Object(App\Description)) #15 _{project path}_vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array) #16 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1679): Illuminate\Events\Dispatcher->fire('eloquent.saved:...', Object(App\Description)) #17 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1514): Illuminate\Database\Eloquent\Model->fireModelEvent('saved', false) #18 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1485): Illuminate\Database\Eloquent\Model->finishSave(Array) #19 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphOneOrMany.php(187): Illuminate\Database\Eloquent\Model->save() #20 _{project path}_database/seeds/RuleTableSeeder.php(139): Illuminate\Database\Eloquent\Relations\MorphOneOrMany->create(Array) #21 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Seeder.php(39): App\Database\Seeds\RuleTableSeeder->run() #22 _{project path}_database/seeds/RulesAndSkillsSeeder.php(18): Illuminate\Database\Seeder->call('App\\Database\\Se...') #23 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): RulesAndSkillsSeeder->run() #24 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2286): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}() #25 _{project path}_vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Closure)) #26 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire() #27 _{project path}_vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #28 _{project path}_vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array) #29 _{project path}_vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 _{project path}_vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #31 _{project path}_vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #32 _{project path}_vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #33 _{project path}_vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #34 _{project path}_vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #35 _{project path}_artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #36 {main} [] []

**Comment by sleimanx2** [comment]
Please can you provide the scenario to reproduce the error ? , I assume it's on save.

**Comment by capitaladot** [comment]
Of course. On sav

**Comment by sleimanx2** [comment]
can you provide me with the output of ```$model->getDocumentData()``` $model is the instance you are trying to seed ...

**Comment by capitaladot** [comment]
So, I went ahead and figured out how to get artisan console debugging to work only to discover that I can't provide the data for $model->getDocumentData(), as the exception is being thrown with the following line:
```
$rule->description()->create([
    'body'=>$eachRule['body']
]);
```
In other words, just as I indicated in the original report, using this trait causes creating models with it to throw the above exception.

**Comment by sleimanx2** [comment]
@capitaladot I've tried to use your input to mimic the call but I can't seem to trigger the exception. It would be easier to track the bug if you create a laravel project where you reconstruct the issue.

**Comment by ChaoticWave** [comment]
I'm pretty sure this is a bug in the `elasticsearch/elasticsearch` composer module. I'm in the process of tracking down the error. It looks like the JSON encoding failed, providing the value `false` in the body of the request. I will update here if I create a PR to that repo.

**Comment by pz6tnk** [comment]
@ChaoticWave so how have you handled this error?

**Comment by ChaoticWave** [comment]
@pz6tnk I think it's got to do with encoding HTML in JSON. It screws up the parser in ES during ingestion. In the end, I didn't use this library in my project. However, I did run into this problem with the Elasticsearch API code. And I've only tried it with ES v2.x. It could be completely fixed in the later versions. I'm not sure.

Sorry for the late reply, I don't log in here much.

**Comment by clyall** [comment]
Hello, this is a super late response, but we ran into this issue as well.

For us, we had a bytea typed field in postgres that was being saved into elastic search. As @ChaoticWave stated, this data type in particular returns false from a json encode. Best advice is to check the types on all the fields you are saving, and figure out which type doesn't play nice with a json encode
