### ISSUE TITLE
Getting error while using search function inside my controller

### ISSUE THREAD

**Issue by sjakhetia** [sleimanx2/plastic#90]
Hi Team,

I am getting an error while using search function inside my controller. 
Below is the response:
**Class 'ONGR\ElasticsearchDSL\Query\FullText\MatchQuery' not found.**

Can you please let me know what I am doing wrong into it. 

Also, Please help me out from this, Thank you in advance.

**Comment by sjakhetia** [comment]
Is anyone has a fix for it?

**Comment by mattrabe** [comment]
Switching to 0.2.7 resolved this issue for me

**Comment by sleimanx2** [comment]
is it still relevant?
