### ISSUE TITLE
Error index_not_found_exception

### ISSUE THREAD

**Issue by dily86** [sleimanx2/plastic#91]
Hi, 
When I run a search with a controller I have this error displayed in the browser:

Missing404Exception in Connection.php line 572: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"articles","index_uuid":"_na_","index":"articles"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"articles","index_uuid":"_na_","index":"articles"},"status":404}

Could you help me, please. Thanks in advance.

**Comment by dily86** [comment]
any ideas ?

**Comment by yao23** [comment]
Check the index articles exist or not, if not, create it and it should work.

**Comment by naddynadeem** [comment]
I have same error
please guide me how to fix it
