### ISSUE TITLE
Dimsav Translatable n+1 issue

### ISSUE THREAD

**Issue by Melcus** [sleimanx2/plastic#92]
There package I am referring to is https://github.com/dimsav/laravel-translatable .
The package works by storing the translations for a model on a separate table.

For  `$model = Model::search()->querystring('*' . $search_keyword . '*' , ['fields' => ['suggestions' ])->get();` 
it queries
```SELECT * FROM `model_trans` WHERE `model_trans`.`model_id` IS NULL and `model_trans`.`model_id` IS not NULL and `model_trans`.`deleted_at` IS NULL```
for every result. This only happens when I have the Translatable trait on the model. 

What would you suggest?
Opened a ticket on the said package as well https://github.com/dimsav/laravel-translatable/issues/343

**Comment by Melcus** [comment]
Any ideas?

**Comment by Melcus** [comment]
Indexing the relationship with another name solved the issue.

**Comment by donmbelembe** [comment]
@Melcus Can you provide more explanation on how you've done it
