### ISSUE TITLE
How to index many phones related to one person?

### ISSUE THREAD

**Issue by warrio4** [sleimanx2/plastic#93]
Hi,

I have a model Person with a 1:N relation with a model Phone (A person can have 1 or many phones)
How is it possible to index in each person document all the phones related to it? Is it even possible?

The purpose is to search a person using his name or his phone number.

I can do it by searching each model separately, but I would like to know if it's possible to combine these two.

**Comment by Melcus** [comment]
In your buildDocument function, add another field

return [
     'id' => $this->id,
     'name' => $this->name,
     'phones' => $this->phones (or how you called the relationship),
];

that's it, you don't even need to recreate the mapping

**Comment by warrio4** [comment]
Awesome, this works..
Just to be clean, I tried to mapp it using
```
            $map->nasted('phones', function(Blueprint $map) {
                $map->long('id');
                $map->string('number');
                $map->string('comment');
                $map->integer('row_order');
            });
```
But if didn't work.

**Comment by warrio4** [comment]
The Phone model is correctly synced thanks to Plastic.

However, the phones contained in the person's document are not. Is there a way to fix this?
