### ISSUE TITLE
How to sync a nested property?

### ISSUE THREAD

**Issue by warrio4** [sleimanx2/plastic#94]
Hello,

I have a model Person indexed to ES. Each person has one or many phones.

```
public function buildDocument()
{
    $data = [
        'id' => $this->id,
        'first_name' => $this->first_name,
        'last_name' => $this->last_name,
        'phones' => $this->phones,
    ];
    return $data;
}
```
Mapping of Person looks like this:
```
public function map()
{
    Map::create($this->getModelType(), function(Blueprint $map){
        $map->long('id');
        $map->string('first_name');
        $map->string('last_name');
        $map->nested('phones', function(Blueprint $map) {
            $map->long('id');
            $map->string('number');
            $map->string('comment');
        });
    },$this->getModelIndex());
}
```

The person is correctly synced except the phones property.

Has Plastic planned something for this issue?
Any hint would be highly appreciated.

**Comment by Melcus** [comment]
On your Phone model, add  `protected $touches = ['person'];`  The `touches` array is where you put all the relationships you want to sync as soon as this Model is updated

**Comment by warrio4** [comment]
It works great thanks to your help. I was gonna change all my model if you didn't help.
If you pass by Belgrade, I'll be glad to invite for a beer :D

**Comment by Melcus** [comment]
Heh. Cheers. Glad you got it working ;)

**Comment by warrio4** [comment]
In case this issue may help others. I'm using polymorphic relations, so I put `protected $touches = ['phonable'];`
