### ISSUE TITLE
Sorting nested objects

### ISSUE THREAD

**Issue by warrio4** [sleimanx2/plastic#97]
Hi,

I am trying to search the model Person and sorting the result by score, then by person.addresses.row_order using the following query:

    $persons = Person::search();
    $persons->should()
        ->match('full_name', $this->keyword);
    $persons
        ->sortBy('_score', 'asc')
        ->sortBy('addresses.row_order', 'desc');
    return $persons->get()->hits();

The query returns the searched result but adresses are not sorted as specified. Am I doing it wrong?
Any hint would be really appreciated.

**Comment by sleimanx2** [comment]
hello @warrio4, please try to get the DSL query as follow `$persons->toDSL()` and check if it's the intended query. 

Please open another issue if you find any problem with the generated query.
