### ISSUE TITLE
How to first check if a connection to a node is available before build/update

### ISSUE THREAD

**Issue by robertzimmerman** [sleimanx2/plastic#99]
Hi,

   Is there a way to check before doing a buildDocument() to create/update my content that there is a node available. incase something happens to the server, it just hangs on saving my model to the db. so if i can stop it, at least the db is updated and i can worry about updating elasticsearch docs. 

sorry. just adding how my build works, i have a modal and a trait, the trait is where i am building the document and its mapped correctly. 

- Thank you

**Comment by sleimanx2** [comment]
I think having the ability to queue the document saving might solve this your issue.
